# this overrides settings in the generated config file
# leave out setting you want to take over (endpoints, globalVars)

web:
  server:
    host: "0.0.0.0"
    port: 8080
  frontend:
    enabled: true
    debug: true
    pprof: true
  api:
    enabled: true

validatorNames:
  inventoryYaml: "${DEVNET_DIR}/generated-validator-ranges.yaml"

#globalVars:
#  additionalGlobalVar: xx

externalTests:
  - file: "https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/pectra-dev/bls-changes.yaml"
    config:
      validatorCount: 100
  - file: https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/pectra-dev/wait-for-slot.yaml
    id: wait1
    config:
      slot: 34
  - file: ./test-consolidations.yaml
