participants:
  - el_type: geth
    el_image: ethpandaops/geth:lightclient-prague-devnet-1-37c4b03
    cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:electra-devnet-1-51d51f5
    validator_count: 2048
  - cl_type: teku
    cl_image: ethpandaops/teku:master-2d2d17b
    el_type: nethermind
    el_image: nethermindeth/nethermind:pectra-fix
    validator_count: 2048
network_params:
  seconds_per_slot: 6
  electra_fork_epoch: 1
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
additional_services:
  - assertoor
  - dora
snooper_enabled: true
assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false