id: execution-spec-tests-dependencies
name: "Setup dependencies for execution spec tests"
timeout: 1h
tasks:
  - name: run_shell
    title: Install dependencies
    config:
      shell: bash
      command: |
        dpkg --add-architecture amd64
        apt-get update
        apt-get install -y build-essential python3 python3-pip libc6:amd64
        rm /usr/lib/python3*/EXTERNALLY-MANAGED 2>/dev/null || true
