id: pectra-execution-spec-tests
name: "Run execution spec tests"
timeout: 1h
config:
  #walletPrivkey: ""
tasks:
  - name: run_shell
    title: Install dependencies
    config:
      shell: bash
      command: |
        dpkg --add-architecture amd64
        apt-get update
        apt-get install -y build-essential python3 python3-pip
        rm /usr/lib/python3*/EXTERNALLY-MANAGED

  - name: check_clients_are_healthy
    title: "Check if at least one client is ready"
    id: clientCheck
    timeout: 5m
    config:
      minClientCount: 1

  - name: get_consensus_specs
    id: consensusSpecs

  - name: run_external_tasks
    title: "Run execution spec tests: eip7702_set_code_tx"
    timeout: 30m
    config:
      testFile: https://raw.githubusercontent.com/ethpandaops/assertoor/master/playbooks/dev/execution-spec-tests-execute.yaml
      testConfig:
        gitRepo: https://github.com/ethereum/execution-spec-tests.git
        gitBranch: fill-execute-modes
        testPath: ./tests/prague/eip7702_set_code_tx/test_set_code_txs.py::test_self_sponsored_set_code
        seedAmount: "100000000000000000000"
        extraFlags: "--fork=Prague"
      testConfigVars:
        rpcEndpoint: "tasks.clientCheck.outputs.goodClients[0].elRpcUrl"
        chainID: "tasks.consensusSpecs.outputs.specs.DEPOSIT_CHAIN_ID"
        privateKey: "walletPrivkey"
